### PR TITLE
move jest to dev dependencies

### PR DESCRIPTION
**Pull request by jakesjews**
This decreases the install size of the package a fair amount

### CODE REVIEW

**Comment by scottkidder** [comment]
I also noticed jest being added to my dependencies. I think I'll pass on making my node_modules any bigger! :laughing:

**Comment by rwjblue** [comment]
Good catch! 

@stefanpenner / @joliss - Either of y'all have a minute to merge + release?

**Comment by stefanpenner** [comment]
OOOPS

**Comment by stefanpenner** [comment]
released as v2.0.2 🎉

**Pull request merged**
